import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Aside } from "./components/Aside";
import { Header } from "./components/Header";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-900`}
            >
                <div className="container mx-auto">
                    <div className="flex flex-col lg:grid lg:grid-cols-4 h-screen md:p-10 gap-6">
                        <Aside />
                        <main className="flex flex-col lg:col-span-3 rounded-lg p-8 bg-zinc-950 gap-10">
                          <Header />
                          {children}
                        </main>
                    </div>
                </div>
            </body>
        </html>
    );
}
